baseURL: 'https://buglix.org/'
languageCode: en-us
title: buglix.org
theme: PaperMod
disqusShortname: buglixorg
enableRobotsTXT: true
googleAnalytics: UA-1998842-2

# defaultContentLanguage: en
# languages:
#   en:
#     title: buglix.org
#     weight: 1
#   sv:
#     title: buglix.org
#     weight: 2

goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true

params:
    defaultTheme: auto
    description: "Emil Erlandssons personal blog"
    author: Emil Erlandsson
    ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: false
    env: production
    comments: true

    homeInfoParams:
        Title: Hello ðŸ‘‹
        Content: Blog of the father of two, gadget connoisseur, writer, traveller, photographer, occasional golfer, runner, services professional who of course is an Apple fanboy.

    socialIcons:
        - name: github
          url: "https://github.com/emilerl"
        - name: twitter
          url: "https://twitter.com/emilerl"
        - name: facebook
          url: "https://facebook.com/emilerl"
        - name: linkedin
          url: "https://www.linkedin.com/in/emilerl/"
        - name: instagram
          url: "https://www.instagram.com/emilerl/"
        - name: medium
          url: "https://medium.com/@emilerl"
        - name: reddit
          url: "https://www.reddit.com/user/emilerl"
        - name: flickr
          url: "https://www.flickr.com/photos/emilerl"
        - name: other
          url: "https://www.thingiverse.com/emilerl"
        - name: "rss"
          url: "https://buglix.org/index.xml"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 20
        - identifier: about
          name: About
          url: /about/
          weight: 10
        - identifier: search
          name: Search
          url: /search/
          weight: 30
